name: stagexl_samples
author: Bernhard Pichler
description: Sample applications showing features of the StageXL library.
homepage: http://www.stagexl.org/

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  stagexl: any
  stagexl_bitmapfont: any
  stagexl_dragonbones: any
  stagexl_flump: any
  stagexl_richtextfield: any
  stagexl_spine: any
  stagexl_gaf: any

transformers:
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives", "--dump-info"]
    minify: true
